# Generated by Django 3.0.4 on 2020-03-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_namee',
            new_name='first_name',
        ),
    ]
