# Generated by Django 3.0.4 on 2020-03-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20200325_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
