# Generated by Django 3.0.4 on 2020-03-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tile',
            new_name='title',
        ),
    ]
