# Generated by Django 3.0.4 on 2020-04-08 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.BooleanField(default=False)),
                ('accept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.Commentary')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(null=True)),
                ('commentary', models.TextField(null=True)),
                ('file', models.FileField(upload_to='result/')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default=False, upload_to='picture/')),
                ('mark', models.IntegerField(null=True)),
                ('xp', models.IntegerField(null=True)),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(default=False, upload_to='file/')),
                ('price', models.IntegerField(null=True)),
                ('deadline', models.DateField(null=True)),
                ('description', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='db.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='proposition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.Post'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='db.Profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Post')),
            ],
        ),
        migrations.AddField(
            model_name='commentary',
            name='author',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='db.Profile'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Post'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='db.Profile')),
                ('sender', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='db.Profile')),
            ],
        ),
    ]
