# Generated by Django 3.0.4 on 2020-04-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='commentary',
            new_name='opinion',
        ),
    ]
