# Generated by Django 3.0.4 on 2020-04-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20200409_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mark',
        ),
    ]
