# Generated by Django 3.0.4 on 2020-04-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='db.Profil'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='db.Profil'),
        ),
    ]
