# Generated by Django 3.0.4 on 2020-04-30 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20200420_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
