# Generated by Django 3.0.4 on 2020-04-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_post_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
