# Generated by Django 3.0.4 on 2020-04-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_mission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='cotation',
            field=models.FloatField(null=True),
        ),
    ]
