# Generated by Django 3.0.4 on 2020-04-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_commentary_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.Commentary')),
                ('proposition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.Post')),
            ],
        ),
    ]
