# Generated by Django 3.0.4 on 2020-05-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='result',
            name='opinion',
        ),
        migrations.AddField(
            model_name='result',
            name='conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='looser',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='looser', to='db.Profile'),
        ),
        migrations.AlterField(
            model_name='result',
            name='winner',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='db.Profile'),
        ),
    ]
