# Generated by Django 3.0.4 on 2020-05-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_result_playerconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confidence',
            field=models.IntegerField(null=True),
        ),
    ]
