# Generated by Django 3.0.4 on 2020-05-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_profile_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nummber',
            field=models.IntegerField(null=True),
        ),
    ]
