# Generated by Django 3.0.4 on 2020-05-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20200501_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='win',
            field=models.IntegerField(null=True),
        ),
    ]
