# Generated by Django 3.0.4 on 2020-05-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_auto_20200501_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confidence',
            field=models.IntegerField(default=100),
        ),
    ]
