# Generated by Django 3.0.4 on 2020-05-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20200501_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nummber',
            new_name='number',
        ),
    ]
