# Generated by Django 3.0.4 on 2020-05-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_auto_20200501_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.FloatField(default=0),
        ),
    ]
