# Generated by Django 3.0.4 on 2020-05-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_profile_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fund',
        ),
    ]
